### ISSUE TITLE
Compiling in MSVC 2013

### ISSUE THREAD

**Issue by fuzzac** [jmacd/xdelta#216]
Hi,

I've been trying to compile xdelta in Visual Studio 2013 and ran into a number off issues with e.g. inlined functions, missing SIZEOF_SIZE_T define, `__attribute__` not supported in MSVC and some Posix function that doesn't exist on Windows. Is Visual Studio still supported for xdelta?

Thanks in advance.

**Comment by dozenow** [comment]
Hi @fuzzac ,
Were you able to compile it in VS 2013? I ran into the same problem. Thanks.

**Comment by zdunker** [comment]
I ran into the same issue, may I ask how you solved this? Thank you.

**Comment by dozenow** [comment]
@zdunker I had this problem and gave up using visual studio. Finally, I switched to use mingw64 to compile it on Windows. It works.

**Comment by OscarKing888** [comment]
I have the same problem, too, but I'm using VS2015. When open xdelta3.vcxproj and compile will get:
xdelta3.h(243): fatal error C1189: #error:  Bad configure script

I checked the compile options in Debug|Win32   C/C++ -> General -> Additional Include Direcories, there is ../xz/include. 

Is some file missed in the github? Also I can't find the config.h :(

**Comment by psikorski** [comment]
I still see that problem. Any advice on resolving it for VS2015?

**Comment by lieser** [comment]
I was able to build it under VS2013. See https://github.com/jmacd/xdelta/pull/231 for what I changed.

**Comment by plaska-verys** [comment]
Sorry to necro such an old thread.  However, it is June 8, 2020, and this issue still exists in every Visual Studio build except the Win32 | Debug build, when using the xdelta3.vcxproj project.  I just ran into it myself.  The reason it works in the one project, is that it has `SIZEOF_SIZE_T` defined in the `PreprocessorDefinitions` for that build configuration.

If anyone is attempting to use the Visual Studio project, and needs to get past this issue, just define `SIZEOF_SIZE_T` appropriately for your build configuration in the C++ Preprocessor Definitions properties.  

Same issue goes for SIZEOF__UNSIGNED_LONG_LONG.

~~I may see about submitting a PR, but since I'm fairly new to xdelta, I have no idea if it will be accepted.~~  Yeah, I don't see any options to ask for contribution/commit access (e.g. in the README.md), nor an option to create a branch to submit a PR on (e.g. in the GitHub dropdown).  I'm guessing the project is not open to community contributions.  Anyway, I opened a ticket:
https://github.com/jmacd/xdelta/issues/258
